version: "3.7"

x-php-config: &php-config
    environment:
        APP_DIR: ${APP_DIR}
        APP_ENV: ${APP_ENV}
        APP_DEBUG: ${APP_DEBUG}
        APP_SECRET: ${APP_SECRET}
        XDEBUG_MODE: ${XDEBUG_MODE}
        PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        MAILER_FROM_APP_EMAIL: ${MAILER_FROM_APP_EMAIL}
        MAILER_DSN: ${MAILER_DSN}
    networks: [ internal ]
    dns: [ 8.8.4.4, 8.8.8.8 ]
services:
    nginx:
        build:
            context: ./docker
            dockerfile: dev/nginx/nginx.dockerfile
            args:
                nginx_image: ${NGINX_IMAGE}
        environment:
            APP_DIR: ${APP_DIR}
        depends_on: [php-fpm]
        networks: [ internal ]
        ports: [ "${HTTP_PORT}:80" ]
        volumes:
            - ./docker/common/nginx/templates:/etc/nginx/templates:ro
            - ./docker/common/nginx/modules-enabled:/etc/nginx/modules-enabled:ro
            - ./docker/common/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./app:${APP_DIR}:cached
    php-fpm:
        build:
            context: ./docker
            dockerfile: dev/php-fpm/php-fpm.dockerfile
            args:
                php_fpm_image: ${PHP_FPM_IMAGE}
                app_dir: ${APP_DIR}
                user: ${USER}
                uid: ${UID}
        <<: *php-config
        volumes:
            - ./app:${APP_DIR}:rw
        extra_hosts:
            - host.docker.internal:host-gateway
    php-cli:
        build:
            context: ./docker
            dockerfile: dev/php-cli/php-cli.dockerfile
            args:
                php_cli_image: ${PHP_CLI_IMAGE}
                app_dir: ${APP_DIR}
                user: ${USER}
                uid: ${UID}
        <<: *php-config
        volumes:
            - ./app:${APP_DIR}:rw

networks:
    internal:
